apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-app
  labels:
    app: kubernetes-app
spec:
  replicas: 1           # come√ßa com 1 pod
  selector:
    matchLabels:
      app: kubernetes-app
  template:
    metadata:
      labels:
        app: kubernetes-app
    spec:
      containers:
        - name: kubernetes-app
          image: kubernetes:1.0   # substitua pelo nome da sua imagem local
          imagePullPolicy: Never   # importante para usar imagem local
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
